---
# This role installs HAProxy and configures it.
- name: modify firewall permission
  ufw: state=enabled policy=allow

- name: Download and install haproxy and socat
  apt: name={{ item }} state=present
  with_items:
  - haproxy
  - socat
- name: enable haproxy settings
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
